insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<В> то время тетрарх <б>Ирод услышал слух об Иисусе',2,1,14,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И сказал своим слугам: Это <а>Иоанн Креститель; он воскрешён из мёртвых, и поэтому эти <б>явления силы <1>действуют через него.',2,1,14,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо Ирод, схватив Иоанна, связал его и посадил в <а>тюрьму из-за <б>Иродиады, жены Филиппа, своего брата.',2,1,14,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо Иоанн говорил ему: Тебе <а>не разрешается иметь её.',2,1,14,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И он хотел убить его, но побоялся толпы, потому что его <а>считали <б>пророком.',2,1,14,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А когда наступил <а>день рождения Ирода, дочь Иродиады танцевала посреди собравшихся и угодила Ироду;',2,1,14,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Поэтому он с клятвой пообещал дать ей, чего бы она ни попросила.',2,1,14,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И она по наущению своей матери говорит: Дай мне здесь же на блюде голову Иоанна Крестителя.',2,1,14,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И царь огорчился, но из-за своих клятв и из-за тех, кто возлежал с ним за трапезой, приказал дать.',2,1,14,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, послав людей, он <1>обезглавил Иоанна в тюрьме.',2,1,14,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И принесли его голову на блюде и дали девушке, а она отнесла своей матери.',2,1,14,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И его <а>ученики пришли, взяли труп и погребли его; и пришли и сообщили Иисусу.',2,1,14,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И Иисус, услышав об этом, <1>удалился оттуда на лодке в пустынное место отдельно от других. А толпы, услышав о том, пешком <2>последовали за Ним из городов.',2,1,14,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он, выйдя, увидел большую толпу, и <а>сжалился над ними, и исцелил их больных.',2,1,14,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А когда наступил вечер, к Нему подошли ученики и сказали: Место это пустынное, и час уже <1>поздний. Отошли толпы, чтобы они пошли в селения и купили себе пищи.',2,1,14,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но Иисус сказал им: Не нужно им уходить. Вы <1а>дайте им <2>есть.',2,1,14,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А они говорят Ему: У нас здесь ничего нет, кроме пяти <1>хлебов и двух рыб.',2,1,14,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Он сказал: <1>Несите их сюда ко Мне.',2,1,14,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, приказав толпам <1>возлечь на траве, Он взял <а>пять хлебов и две рыбы, и, <2б>взглянув на небо, <в>благословил и <3г>преломил хлебы, и <4>дал их ученикам, а ученики — толпам.',2,1,14,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И все ели и насытились. И собрали то, что осталось от <а>кусков: <1>двенадцать полных коробов.',2,1,14,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А тех, кто ел, было около пяти тысяч мужчин — не считая женщин и детей.',2,1,14,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И Он сразу же <1>принудил учеников войти в лодку и плыть раньше Его на другую сторону, пока Он отсылает толпы.',2,1,14,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, отослав толпы, Он поднялся на гору отдельно от других <1а>помолиться. И когда наступила <2>ночь, Он был там один.',2,1,14,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А лодка уже была <1>посреди моря; её било волнами, потому что ветер был встречный.',2,1,14,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И в <1>четвёртую <а>стражу ночи Он пришёл к ним, <2б>идя по морю.',2,1,14,25);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И ученики, увидев, что Он идёт по морю, <а>встревожились и сказали: Это призрак! — и от страха закричали.',2,1,14,26);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но Иисус сразу же заговорил с ними и сказал: <а>Смелее! <1>Это Я. <б>Не бойтесь.',2,1,14,27);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И в ответ Ему Пётр сказал: Господь, если это Ты, прикажи мне подойти к Тебе по воде.',2,1,14,28);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он сказал: Подойди. — И Пётр, сойдя с лодки, пошёл по воде и подошёл к Иисусу.',2,1,14,29);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но, <1>видя сильный ветер, он испугался и, начав тонуть, закричал: Господь, <а>спаси меня!',2,1,14,30);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Иисус сразу же протянул руку, подхватил его и говорит ему: <а>Маловер, зачем ты <1б>усомнился?',2,1,14,31);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда они поднялись в лодку, <1>ветер утих.',2,1,14,32);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И те, кто был в лодке, <а>поклонились Ему и сказали: Истинно Ты <1б>Сын Божий.',2,1,14,33);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И они переправились и подошли к берегу в <б>Геннисарете.',2,1,14,34);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, узнав Его, жители того места послали весть по всей той окрестности и привели к Нему всех больных.',2,1,14,35);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И они умоляли Его, чтобы им только коснуться <1а>кистей на Его одежде. И все, которые <б>коснулись, были полностью <2>исцелены.',2,1,14,36);