insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Тогда <1>приходят к Иисусу из <б>Иерусалима фарисеи и книжники и говорят:',2,1,15,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Почему Твои ученики <1>преступают <а>предание старцев? Ибо они <б>не омывают руки, когда едят хлеб.',2,1,15,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Он сказал им в ответ: Почему и вы <1>преступаете заповедь Божью из-за вашего предания?',2,1,15,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо Бог сказал: «<1а>Почитай отца и мать», и «Кто <2б>злословит отца или мать, тот <3>пусть будет предан смерти».',2,1,15,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А вы говорите: «Кто скажет отцу или матери: «То, что было бы тебе пользой от меня, теперь <1>дар Богу»,',2,1,15,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тот ни в коем случае не обязан почитать своего отца или свою мать». И вы лишили силы слово Божье из-за вашего предания.',2,1,15,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<1а>Лицемеры! Хорошо пророчествовал о вас Исайя, который говорит:',2,1,15,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('«<а>Этот народ губами чтит Меня, но их <1>сердце далеко отстоит от Меня;',2,1,15,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но <1>тщетно они поклоняются Мне, уча <а>человеческим заповедям как учениям».',2,1,15,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, подозвав толпу, Он сказал им: <а>Слушайте и понимайте:',2,1,15,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Не то, что входит в уста, <а>оскверняет человека, а то, что исходит из уст, — вот что <1>оскверняет человека.',2,1,15,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда ученики подошли и говорят Ему: Знаешь ли Ты, что фарисеи, услышав это слово, преткнулись?',2,1,15,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он сказал в ответ: Всякое растение, которое Мой небесный Отец <1>не асажал, будет <б>вырвано с корнем.',2,1,15,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Оставьте их. Они — <1а>слепые поводыри слепых; а если слепой ведёт слепого, то оба упадут в яму.',2,1,15,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Пётр сказал Ему в ответ: Объясни нам эту притчу.',2,1,15,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Он сказал: Неужели и вы всё ещё <а>непонятливы?',2,1,15,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Разве вы не понимаете, что всё, что входит в уста, попадает в <а>желудок и отправляется в сточную канаву?',2,1,15,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А то, что исходит из уст, из сердца выходит; и это <а>оскверняет человека.',2,1,15,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо из <а>сердца выходят <1б>злые рассуждения, убийства, <в>прелюбодеяния, блудодеяния, кражи, лжесвидетельства, хулы.',2,1,15,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Вот что оскверняет человека, а есть неомытыми руками — это не оскверняет человека.',2,1,15,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И, выйдя оттуда, Иисус удалился в земли <1б>Тира и Сидона.',2,1,15,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И вот, одна <1а>хананеянка вышла из тех пределов и кричала: Смилуйся надо мной, <2>Господь, <б>Сын Давида! Мою дочь жестоко мучит бес.',2,1,15,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но Он не ответил ей ни слова. И Его ученики, подойдя, просили Его: Отошли её, потому что она кричит позади нас.',2,1,15,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но Он сказал в ответ: Я был <1>послан только к потерянным овцам <а>дома Израиля.',2,1,15,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А она, подойдя, <1а>поклонялась Ему и говорила: <2>Господь, помоги мне!',2,1,15,25);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Он сказал в ответ: Нехорошо взять <1>хлеб детей и бросить <2а>собачонкам.',2,1,15,26);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А она сказала: Да, Господь, ведь и собачонки едят <1>крошки, которые падают со <а>стола их хозяев.',2,1,15,27);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда Иисус сказал ей в ответ: О женщина, велика твоя <а>вера! Пусть <б>будет тебе, как ты хочешь. — И с того <в>часа её дочь была исцелена.',2,1,15,28);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И Иисус, уйдя оттуда, пришёл к <1б>Галилейскому морю и, поднявшись на <в>гору, сел там.',2,1,15,29);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И пришли к Нему большие толпы, ведя с собой хромых, слепых, увечных, немых и многих других больных; и <1>положили их у Его ног, и Он исцелил их,',2,1,15,30);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Так что толпа удивлялась, видя, что <а>немые говорят, увечные здоровы, хромые ходят, а <б>слепые видят. И они <в>прославляли <г>Бога Израиля.',2,1,15,31);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('аА Иисус, подозвав Своих учеников, сказал: Мне бжалко эту толпу, потому что они уже три дня находятся со Мной и им нечего есть. А отсылать их голодными 1не хочу, чтобы они не ослабели в пути.',2,1,15,32);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А ученики говорят Ему: Откуда нам в <1>пустынном месте взять столько хлебов, чтобы <а>насытить такую толпу?',2,1,15,33);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Иисус говорит им: <1>Сколько у вас хлебов? — И они сказали: Семь, и несколько рыбок.',2,1,15,34);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, приказав толпе возлечь на землю,',2,1,15,35);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Он <1>взял <а>семь хлебов и рыбу и, воздав <б>благодарение, преломил их и стал давать ученикам, а ученики — толпам.',2,1,15,36);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И все ели и насытились. И собрали то, что осталось от <>акусков: семь полных корзин.',2,1,15,37);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А тех, кто ел, было четыре тысячи мужчин — не считая женщин и детей.',2,1,15,38);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, отослав толпы, Он вошёл в лодку и прибыл в пределы Магадана.',2,1,15,39);
