insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда 1Иисус был уведён Духом в апустыню, чтобы 2бискусил Его 3вдьявол.',2,1,4,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, проведя в апосте 1бсорок дней и сорок ночей, после Он ощутил вголод.',2,1,4,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И 1аискуситель, подойдя, сказал Ему: Если Ты 2бСын Божий, скажи, чтобы эти 3камни стали хлебами.',2,1,4,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Он сказал в ответ: 1Написано: «2аНе одним 3хлебом будет жить человек, но всяким 4бсловом, исходящим через 5уста Божьи».',2,1,4,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда дьявол берёт Его в асвятой город, и ставит Его на 1крыло 2бхрама,',2,1,4,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И говорит Ему: Если Ты аСын Божий, 1бросься вниз; ибо 2написано: «бСвоим ангелам Он даст повеление о Тебе, и они понесут Тебя на руках, чтобы Ты не споткнулся Твоей ногой о камень».',2,1,4,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Иисус сказал ему: 1Ещё написано: «аНе 2испытывай Господа, твоего Бога».',2,1,4,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Опять дьявол берёт Его на очень высокую гору и показывает Ему все 1ацарства бмира и их вславу.',2,1,4,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И он сказал Ему: 1Всё это я дам Тебе, если Ты, пав, апоклонишься мне.',2,1,4,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда Иисус говорит ему: Отойди, 1аСатана! Ибо написано: «бГосподу, твоему Богу, поклоняйся и Ему 2водному служи».',2,1,4,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда дьявол 1оставляет Его, и вот, 2пришли аангелы и служили Ему.',2,1,4,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А услышав, что аИоанн был отдан под стражу, Он 1удалился в бГалилею.',2,1,4,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, оставив аНазарет, Он пришёл и поселился в бКапернауме, приморском городе в пределах вЗавулона и гНеффалима,',2,1,4,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Чтобы исполнилось сказанное через пророка Исайю, который говорит:',2,1,4,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('«аЗемля Завулона и земля Неффалима, путь к морю, за Иорданом, 1Галилея языческая —',2,1,4,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Народ, сидящий во тьме, увидел 1великий асвет; и сидящим в области и тени смерти — им взошёл свет».',2,1,4,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('С того времени Иисус начал проповедовать и говорить: 1аКайтесь, ибо приблизилось царство небес.',2,1,4,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, проходя авозле Галилейского 1моря, Он увидел двух братьев: бСимона, называемого Петром, и Андрея, его брата, которые 2закидывали 3сеть в море, ибо они были рыбаками.',2,1,4,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он говорит им: аИдите за Мной, и Я сделаю вас 1ловцами людей.',2,1,4,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И они, сразу же оставив сети, 1апоследовали за Ним.',2,1,4,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, пройдя оттуда дальше, Он увидел других двух братьев: Иакова, сына Зеведея, и аИоанна, его брата, в лодке с Зеведеем, их отцом, которые 1латали свои сети, — и бпризвал их.',2,1,4,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И они, сразу же оставив лодку и своего отца, 1апоследовали за Ним.',2,1,4,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И ходил Иисус по всей Галилее, уча в их 1асинагогах, и проповедуя 2бблаговестие царства, и висцеляя всякий недуг и всякую болезнь в народе.',2,1,4,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И пошёл слух о Нём по всей Сирии; и привели к Нему всех больных, одолеваемых различными недугами и мучениями, и аодержимых бесами, и страдающих падучей болезнью, и парализованных, и Он исцелил их.',2,1,4,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И за Ним последовали большие 1атолпы из Галилеи, 2Десятиградия, Иерусалима, Иудеи и из-за Иордана.',2,1,4,25);
