insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, увидев атолпы, Он 1поднялся на бгору. И когда Он сел, подошли к Нему Его 2ученики. ',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, аоткрыв уста, Он учил их и говорил:',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('1Блаженны 2анищие 3духом, ибо их есть 4бцарство небес.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Блаженны 1аскорбящие, ибо они будут 2бутешены. ',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Блаженны 1акроткие, ибо они 2бунаследуют землю.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Блаженны алчущие и ажаждущие 1бправедности, ибо они 2внасытятся',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Блаженны 1амилостивые, ибо им будет 2явлена милость. ',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Блаженны 1ачистые сердцем, ибо они 2бувидят Бога.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Блаженны 1амиротворцы, ибо они будут названы 2бсыновьями Божьими.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Блаженны 1агонимые за бправедность, ибо 2их есть вцарство небес.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Блаженны вы, когда будут 1апоносить вас, и бгнать, и лживо говорить против вас всякое взло 2из-за Меня.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('аРадуйтесь и ликуйте, ибо велика ваша 1бнаграда на небесах; ибо так вгнали 2пророков, которые были до вас.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('1Вы 2асоль земли. Но если соль станет 3бпресной, чем сделать её солёной? Она уже вни на что не годна, разве только 4гвыбросить её, чтобы её 5топтали люди.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Вы 1асвет мира. Невозможно, чтобы 2бгород, расположенный на горе, был скрыт.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, зажигая асветильник, не ставят его под 1сосуд, а ставят на 2бподставку, и он сияет всем, кто в доме.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Пусть так же асияет ваш свет перед людьми, чтобы они видели ваши 1бдобрые дела и 2впрославляли вашего 3Отца, который на небесах.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('1Не думайте, что Я пришёл упразднить азакон или пророков; Я пришёл не упразднить, а 2бисполнить. ',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо истинно говорю вам: пока не уйдёт 1анебо и земля, ни одна 2йота и ни одна 3чёрточка ни в коем случае не уйдёт из закона, пока всё не произойдёт.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, кто отменит одну из амалейших из этих 1заповедей и так научит людей, будет назван бмалейшим в вцарстве небес; а кто выполнит их и научит им, тот будет назван гвеликим в царстве небес.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо говорю вам, что если ваша 1аправедность не превзойдёт праведности 2книжников и фарисеев, то вы ни в коем случае не 3бвойдёте в царство небес.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Вы слышали, что древним было сказано: «аНе убивай; а кто убьёт, будет подлежать бсуду».',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А 1Я говорю вам, что всякий, кто 2агневается на своего 3брата, будет подлежать 4бсуду. А кто скажет своему брату: «5Раќа», — будет подлежать суду 6всинедриона; а кто скажет: «7Мор́э», — будет подлежать 8гГеенне огненной. ',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, если ты будешь приносить свой 1адар на 2бжертвеннике и там вспомнишь, что твой вбрат имеет 3что-то против тебя,',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('То оставь там свой дар перед жертвенником и 1прежде иди и 2апомирись со своим братом, и тогда приходи и приноси свой дар.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('1Скорее благоволи к своему 2апротивнику в суде, пока ты с ним 3в пути, чтобы не 4отдал тебя противник судье, а судья служителю, и ты не был брошен в тюрьму.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Истинно говорю тебе: ни в коем случае не 1выйдешь оттуда, пока не авыплатишь последнего 2кодранта.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Вы слышали, что было сказано: «аНе прелюбодействуй».',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Я говорю вам, что всякий, кто асмотрит на женщину с тем, чтобы вожделеть её, уже бпрелюбодействовал с ней в своём 1всердце.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Если же твой правый аглаз служит для тебя преткновением, 1вырви его и брось от себя, ибо лучше для тебя, чтобы погиб один из твоих членов, чем чтобы всё твоё тело было брошено в 2бГеенну.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И если твоя правая арука служит для тебя преткновением, 1отруби её и брось от себя, ибо лучше для тебя, чтобы погиб один из твоих членов, чем чтобы всё твоё тело пошло в бГеенну.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И было сказано: «аКто 1разведётся со своей женой, пусть даст ей разводное свидетельство».',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Я говорю вам, что 1всякий, кто аразводится со своей женой, кроме как по причине 2блуда, побуждает её прелюбодействовать, и кто женится на разведённой, прелюбодействует.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ещё вы слышали, что древним было сказано: «1аНе нарушай клятву, а 2бисполняй перед Господом свои клятвы».',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Я говорю вам, чтобы вы ане клялись совсем: ни 1бнебом, потому что это престол Божий;',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ни аземлёй, потому что это подножие Его ног; ни на Иерусалим, потому что это бгород великого Царя;',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И своей головой не клянись, потому что не можешь ни одного волоса сделать белым или чёрным',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А пусть ваше слово будет «1ада, да», «нет, нет»; ибо что сверх этого, то 2от 3блукавого.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Вы слышали, что было сказано: «аГлаз за глаз и зуб за зуб».',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Я говорю вам, чтобы вы ане противились злому человеку; напротив, кто ббьёт тебя по правой щеке, 1поверни к нему и другую.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И тому, кто хочет асудиться с тобой и взять твой 1хитон, — уступи ему и плащ;',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И кто заставит тебя идти одну 1милю — иди с ним две.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тому, кто просит у тебя, 1адай, и от того, кто хочет у тебя бзанять, не отворачивайся.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Вы слышали, что было сказано: «аЛюби твоего ближнего и ненавидь твоего бврага».',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Я говорю вам: алюбите своих врагов и бмолитесь за тех, кто вгонит вас,',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Чтобы стать вам 1асыновьями вашего Отца, который на небесах, потому что Он бвозводит Своё солнце над злыми и добрыми и 2посылает вдождь на справедливых и несправедливых.',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо если вы будете алюбить тех, кто любит вас, какая вам 1награда? Разве не то же самое делают и 2сборщики налогов?',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И если будете приветствовать только своих братьев, что особенного делаете? Разве не то же самое делают и аязычники?',2,1,5,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, вы будьте 1асовершенны, бкак совершенен ваш небесный Отец.',2,1,5,1);
