# Generated by Django 4.2.1 on 2023-05-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('author', models.TextField()),
                ('when', models.TextField()),
                ('where', models.TextField()),
                ('whom', models.TextField()),
                ('topic', models.TextField()),
                ('chapter_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chapter', models.IntegerField(default=1)),
                ('verse', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.book')),
                ('testament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.testament')),
            ],
        ),
    ]
