# Generated by Django 4.2.1 on 2023-07-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='bible_note_code_2c5fc6_idx')],
            },
        ),
    ]
