# Generated by Django 4.2.1 on 2023-06-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['verse']},
        ),
        migrations.AlterField(
            model_name='verse',
            name='book',
            field=models.IntegerField(),
        ),
    ]
