# Generated by Django 4.2.1 on 2023-07-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
