# Generated by Django 4.2.1 on 2023-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0006_book_bible_name_book_chapter_ready'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['bible_name'], name='bible_book_bible_n_1e6c51_idx'),
        ),
    ]
