# Generated by Django 4.2.1 on 2023-06-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0008_alter_verse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['verse']},
        ),
    ]
