insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И, призвав к Себе <1>двенадцать Своих учеников, Он дал им <2>власть над нечистыми духами, чтобы они изгоняли их и <б>исцеляли всякий недуг и всякую болезнь.',2,1,10,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>А имена двенадцати <1>апостолов таковы: первый — <б>Симон, называемый Петром, и Андрей, его брат; <в>Иаков, сын Зеведея, и Иоанн, его брат;',2,1,10,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Филипп и Варфоломей, <б>Фома и <1в>Матфей, <2>сборщик налогов; Иаков, сын Алфея, и <3>Фаддей;',2,1,10,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Симон <1>Кананит и Иуда <2а>Искариот, который и <3>предал Его.',2,1,10,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Этих двенадцать <а>послал Иисус, повелев им: На дорогу к <1б>язычникам не идите и ни в какой <в>самарийский город не входите,',2,1,10,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А идите вместо того к потерянным <а>овцам дома <б>Израиля.',2,1,10,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда пойдёте, проповедуйте: «<1>Приблизилось <а>царство небес».',2,1,10,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Больных исцеляйте, мёртвых воскрешайте, прокажённых очищайте, бесов изгоняйте. <б>Даром получили — даром давайте.',2,1,10,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<1а>Не набирайте себе ни золота, ни серебра, ни меди в ваши пояса,',2,1,10,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ни котомки в дорогу, ни двух хитонов, ни сандалий, ни посоха; ибо <а>работник достоин своей пищи.',2,1,10,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И в какой бы город или селение вы ни вошли, выясните, кто в нём достоин, и там оставайтесь, пока не уйдёте.',2,1,10,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, входя в дом, приветствуйте его.',2,1,10,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И если дом будет достоин, пусть ваш мир придёт на него, а если не будет достоин, пусть ваш мир возвратится к вам.',2,1,10,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А если кто-нибудь не примет вас и не послушает ваших слов, то, выходя из того дома или города, <а>стряхните пыль с ваших ног.',2,1,10,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Истинно говорю вам: <1>легче будет земле <а>Содома и Гоморры в день суда, чем тому городу.',2,1,10,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Вот, Я посылаю вас как <а>овец посреди <б>волков. Итак, будьте <1>благоразумны, как <в>змеи, и бесхитростны, как <г>голуби.',2,1,10,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И <а>остерегайтесь людей, ибо они будут <1>отдавать вас в <2б>синедрионы и <в>бичевать вас в своих синагогах.',2,1,10,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И поведут вас к <1>правителям и <а>царям за Меня для <б>свидетельства им и язычникам.',2,1,10,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Но когда будут отдавать вас в их руки, не <б>беспокойтесь о том, как или что говорить, ибо в тот час вам будет дано, что говорить;',2,1,10,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо не вы говорите, а <1а>Дух вашего Отца говорит в вас.',2,1,10,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И отдаст <1>брат брата на смерть, а отец — дитя, и восстанут <а>дети на родителей и умертвят их.',2,1,10,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И будете <а>ненавидимы всеми из-за Моего имени. Но кто <б>вытерпит до конца, тот будет <1>спасён.',2,1,10,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А когда будут гнать вас в этом <а>городе, <б>бегите в другой. Ибо истинно говорю вам: ещё ни в коем случае не <1>обойдёте города Израиля, как придёт <в>Сын Человеческий.',2,1,10,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Ученик не <1>выше учителя, и <б>раб не выше своего господина.',2,1,10,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Достаточно для ученика, чтобы он стал как его учитель, и раб — как его господин. Если Хозяина дома назвали <1а>Веельзевулом, то тем более Его домашних!',2,1,10,25);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Итак, не бойтесь их; ибо нет ничего <б>скрытого, что не будет открыто, и ничего <в>тайного, что не сделается известным.',2,1,10,26);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Что говорю вам в темноте, говорите при свете; и что слышите на ухо, проповедуйте на <а>крышах.',2,1,10,27);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И не <а>бойтесь тех, кто убивает тело, но не может убить душу, а лучше <б>бойтесь <1>Того, кто может и душу, и тело <в>уничтожить в <2г>Геенне.',2,1,10,28);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Разве не продаются два воробья за <1>ассарий? И ни один из них не упадёт на землю без ведома вашего Отца.',2,1,10,29);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А у вас даже <а>волосы на голове все исчислены.',2,1,10,30);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, не бойтесь; вы <а>дороже множества воробьёв.',2,1,10,31);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, всякий, кто <а>исповедает <1>во Мне перед людьми, — <б>исповедаю и Я <2>в нём перед Моим Отцом, который на небесах.',2,1,10,32);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А тот, кто <а>отречётся от Меня перед людьми, — <1>отрекусь и Я от него перед Моим Отцом, который на небесах.',2,1,10,33);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Не думайте, что Я пришёл принести мир на землю; Я <1>пришёл принести не мир, а меч.',2,1,10,34);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо Я пришёл разделить: человека — с его <а>отцом, дочь — с матерью и невестку — со свекровью.',2,1,10,35);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И <а>врагами человека будут его <1>домашние.',2,1,10,36);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тот, кто любит <а>отца или мать <1>больше, чем Меня, не достоин Меня; и тот, кто любит сына или дочь больше, чем Меня, не достоин Меня;',2,1,10,37);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И кто не <1>берёт свой <а>крест и не <б>следует за Мной, не достоин Меня.',2,1,10,38);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Кто <1>найдёт свою <а>душу-жизнь, тот потеряет её, а кто потеряет свою душу-жизнь ради Меня, тот найдёт её.',2,1,10,39);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тот, кто <1а>принимает вас, Меня принимает, а тот, кто <б>Меня принимает, принимает Пославшего Меня.',2,1,10,40);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тот, кто <1а>принимает <2>пророка во имя пророка, получит награду пророка; и тот, кто принимает праведника во имя праведника, получит награду праведника.',2,1,10,41);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И кто напоит одного из этих <а>маленьких людей только <б>чашей холодной воды во имя ученика, — истинно говорю вам, тот ни в коем случае не потеряет своей <1>награды.',2,1,10,42);
