insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Родословие <1>Иисуса <2б>Христа, <3в>сына Давида, <4г>сына Авраама:',2,1,1,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Авраам родил <1а>Исаака, Исаак родил <2б>Иакова, Иаков родил <3в>Иуду и его <4г>братьев,',2,1,1,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Иуда родил <1а>Фареса и Зару от <2>Фамари, Фарес родил <б>Хецрона, Хецрон родил Арама,',2,1,1,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Арам родил Аминадава, Аминадав родил Наассона, Наассон родил Салмона,',2,1,1,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Салмон родил Вооза от <1а>Рахав, <2б>Вооз родил Оведа от <3в>Руфи, Овед родил <4г>Иессея,',2,1,1,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Иессей родил <1а>царя <2б>Давида. Давид родил <3в>Соломона от той, что прежде была <4г>женой Урии,',2,1,1,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Соломон родил <1а>Ровоама, Ровоам родил Авию, Авия родил Асу,',2,1,1,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Аса родил Иосафата, Иосафат родил Иорама, <1>Иорам родил Озию,',2,1,1,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Озия родил Иофама, Иофам родил Ахаза, Ахаз родил Эзекию,',2,1,1,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Эзекия родил Манассию, Манассия родил Амона, Амон родил Иосию.',2,1,1,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<1>Иосия родил <2а>Иехонию и его <3>братьев во времена <4б>переселения в Вавилон.',2,1,1,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А после <1>переселения в Вавилон Иехония родил <а>Салафиила, Салафиил родил <2б>Зоровавеля,',2,1,1,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Зоровавель родил Авиуда, Авиуд родил Элиакима, Элиаким родил Азора,',2,1,1,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Азор родил Садока, Садок родил Ахима, Ахим родил Элиуда,',2,1,1,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Элиуд родил Элеазара, Элеазар родил Матфана, Матфан родил Иакова,',2,1,1,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А <1>Иаков родил <2а>Иосифа, мужа <3б>Марии, от которой вродился <г>Иисус, называемый <4д>Христом.',2,1,1,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, <1>всех поколений от Авраама <2>до Давида — четырнадцать поколений, и от Давида <3>до переселения в Вавилон — четырнадцать поколений, и от переселения в Вавилон <4>до Христа — четырнадцать поколений.',2,1,1,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Происхождение Иисуса Христа было таково: после того как Его мать <б>Мария была обручена с Иосифом, прежде чем они сочетались, оказалось, что она носит в чреве <1>от <в>Святого Духа',2,1,1,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Иосиф, её муж, будучи <1а>праведным и не желая <б>выставить её на позор, решил тайно <2>отослать её.',2,1,1,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но когда он обдумывал это, вот, <а>ангел Господень явился ему во <б>сне и сказал: Иосиф, сын Давида, не бойся принять Марию, твою жену, ибо <1>родившееся в ней — <2>от <в>Святого Духа.',2,1,1,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И родит она <а>сына, и ты назовёшь Его именем <1б>Иисус, ибо это Он вспасёт Свой народ от их грехов.',2,1,1,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А произошло всё это, чтобы <а>исполнилось сказанное Господом через <1>пророка, который говорит:',2,1,1,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('«Вот, <а>дева понесёт в чреве и родит <1>сына, и назовут Его именем <2б>Эммануил» (что в переводе означает «<в>Бог <3>с нами»).',2,1,1,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, пробудившись от сна, Иосиф сделал, как повелел ему ангел Господень, и принял к себе свою жену.',2,1,1,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И он не знал её, пока она не <1>родила сына. И он назвал Его именем <а>Иисус.',2,1,1,25);
