insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('аРодословие 1Иисуса 2бХриста, 3всына Давида, 4гсына Авраама:',2,1,1,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Авраам родил 1аИсаака, Исаак родил 2бИакова, Иаков родил 3вИуду и его 4гбратьев,',2,1,1,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Иуда родил 1аФареса и Зару от 2Фамари, Фарес родил бХецрона, Хецрон родил Арама,',2,1,1,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Арам родил Аминадава, Аминадав родил Наассона, Наассон родил Салмона,',2,1,1,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Салмон родил Вооза от 1аРахав, 2бВооз родил Оведа от 3вРуфи, Овед родил 4гИессея,',2,1,1,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Иессей родил 1ацаря 2бДавида. Давид родил 3вСоломона от той, что прежде была 4гженой Урии,',2,1,1,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Соломон родил 1аРовоама, Ровоам родил Авию, Авия родил Асу,',2,1,1,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Аса родил Иосафата, Иосафат родил Иорама, 1Иорам родил Озию,',2,1,1,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Озия родил Иофама, Иофам родил Ахаза, Ахаз родил Эзекию,',2,1,1,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Эзекия родил Манассию, Манассия родил Амона, Амон родил Иосию.',2,1,1,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('1Иосия родил 2аИехонию и его 3братьев во времена 4бпереселения в Вавилон.',2,1,1,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А после 1переселения в Вавилон Иехония родил аСалафиила, Салафиил родил 2бЗоровавеля,',2,1,1,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Зоровавель родил Авиуда, Авиуд родил Элиакима, Элиаким родил Азора,',2,1,1,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Азор родил Садока, Садок родил Ахима, Ахим родил Элиуда,',2,1,1,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Элиуд родил Элеазара, Элеазар родил Матфана, Матфан родил Иакова,',2,1,1,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А 1Иаков родил 2аИосифа, мужа 3бМарии, от которой вродился гИисус, называемый 4дХристом.',2,1,1,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, 1всех поколений от Авраама 2до Давида — четырнадцать поколений, и от Давида 3до переселения в Вавилон — четырнадцать поколений, и от переселения в Вавилон 4до Христа — четырнадцать поколений.',2,1,1,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('аПроисхождение Иисуса Христа было таково: после того как Его мать бМария была обручена с Иосифом, прежде чем они сочетались, оказалось, что она носит в чреве 1от вСвятого Духа',2,1,1,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Иосиф, её муж, будучи 1аправедным и не желая бвыставить её на позор, решил тайно 2отослать её.',2,1,1,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но когда он обдумывал это, вот, аангел Господень явился ему во бсне и сказал: Иосиф, сын Давида, не бойся принять Марию, твою жену, ибо 1родившееся в ней — 2от вСвятого Духа.',2,1,1,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И родит она асына, и ты назовёшь Его именем 1бИисус, ибо это Он вспасёт Свой народ от их грехов.',2,1,1,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А произошло всё это, чтобы аисполнилось сказанное Господом через 1пророка, который говорит:',2,1,1,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('«Вот, адева понесёт в чреве и родит 1сына, и назовут Его именем 2бЭммануил» (что в переводе означает «вБог 3с нами»).',2,1,1,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, пробудившись от сна, Иосиф сделал, как повелел ему ангел Господень, и принял к себе свою жену.',2,1,1,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И он не знал её, пока она не 1родила сына. И он назвал Его именем аИисус.',2,1,1,25);
