insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он, войдя в лодку, переправился и прибыл в <1а>Свой город.',2,1,9,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И вот, принесли к Нему парализованного, лежащего на постели. И Иисус, <1>увидев их <б>веру, сказал парализованному: <в>Смелее, дитя! <г>Прощаются твои <2>грехи.',2,1,9,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И вот, некоторые из <1>книжников сказали про себя: Этот человек <2а>богохульствует.',2,1,9,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Иисус, <1а>зная их <2>мысли, сказал: Зачем вы <б>мыслите злое в ваших сердцах?',2,1,9,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо что <1>легче: сказать: «Прощаются твои грехи», или сказать: «<2>Встань и ходи»?',2,1,9,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но чтобы вы знали, что <а>Сын Человеческий имеет <1>власть на земле <б>прощать грехи, — тогда Он говорит парализованному: Встань, <2в>возьми свою постель и <3>иди к себе домой.',2,1,9,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И он, <1>встав, ушёл к себе домой.',2,1,9,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А толпы, увидев это, <а>испугались и <б>прославили Бога, давшего такую власть людям.',2,1,9,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И, идя оттуда дальше, Иисус увидел человека, сидящего на месте сбора налогов, которого звали <1б>Матфеем, и говорит ему: <2в>Следуй за Мной. — И тот встал и <3>последовал за Ним.',2,1,9,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда Он возлежал за трапезой в <1>доме, вот, пришли многие <2а>сборщики налогов и <б>грешники и возлежали с Иисусом и Его учениками.',2,1,9,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, увидев это, <1>фарисеи сказали Его ученикам: <2>Почему ваш Учитель ест со сборщиками налогов и грешниками?',2,1,9,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Он, услышав это, сказал: Не сильным нужен <1>врач, а <2>больным.',2,1,9,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Пойдите же, <1>изучите, что значит: «<2а>Милости хочу, а не <б>жертвы». Ибо Я пришёл призвать не <3в>праведников, а <г>грешников.',2,1,9,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>Тогда подходят к Нему <б>ученики Иоанна и говорят: <1>Почему мы и фарисеи <2в>постимся <3>много, а Твои <г>ученики <4>не постятся?',2,1,9,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Иисус сказал им: Разве могут <1>сыновья свадебного чертога скорбеть, пока с ними <2а>жених? Но придут <б>дни, когда жених будет <3>взят от них, и тогда они будут <в>поститься.',2,1,9,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Никто не ставит заплату из <1>небелёной ткани на <2>старую одежду, ибо пришитое к ней отрывает от одежды и дыра становится хуже.',2,1,9,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И не наливают <1>молодое вино в <2а>старые мехи; а иначе рвутся мехи, и вино выливается, и мехи пропадают; напротив, молодое вино наливают в <3б>новые мехи, и сохраняется и то и другое.',2,1,9,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<1а>Когда Он говорил им это, вот, пришёл один <2>начальник и <б>поклонялся Ему, говоря: Моя дочь только что умерла, но приди, возложи на неё руку, и она оживёт.',2,1,9,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Иисус встал и последовал за ним, и Его ученики тоже.',2,1,9,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И вот, женщина, <1>двенадцать лет страдавшая <2а>кровотечением, <3>подойдя сзади, коснулась <4б>кистей на Его одежде.',2,1,9,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо она говорила про себя: Если только <а>коснусь Его одежды, <1>буду <2>исцелена.',2,1,9,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Иисус, обернувшись и увидев её, сказал: <а>Смелее, дочь! Твоя <б>вера исцелила тебя. — И с того часа женщина была исцелена.',2,1,9,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда Иисус пришёл в <1>дом начальника и увидел играющих на флейте и толпу в смятении,',2,1,9,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Он сказал: Уходите, ибо девочка не умерла, а <а>спит. — И они стали насмехаться над Ним.',2,1,9,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А когда <1>толпу <а>выгнали, Он вошёл и <б>взял её за руку, и девочка <2>встала.',2,1,9,25);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И пошла эта <а>молва по всей той земле.',2,1,9,26);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И когда Иисус шёл оттуда дальше, за Ним последовали двое <1>слепых, которые кричали: Смилуйся над нами, <2б>Сын Давида!',2,1,9,27);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда Он вошёл в <1>дом, слепые подошли к Нему, и Иисус говорит им: Верите, что Я могу это сделать? — Они говорят Ему: Да, Господь.',2,1,9,28);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда Он <а>коснулся их глаз и сказал: Согласно вашей <б>вере пусть <в>будет вам.',2,1,9,29);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И у них <1а>открылись глаза. И Иисус строго повелел им: <б>Смотрите, чтобы никто не знал!',2,1,9,30);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но они, выйдя, <а>разнесли молву о Нём по всей той земле.',2,1,9,31);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда они выходили, вот, привели к Нему <1а>немого человека, одержимого бесом.',2,1,9,32);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда бес был изгнан, немой <1а>заговорил. И толпы удивились и говорили: Никогда такого не было <б>видано в Израиле.',2,1,9,33);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А фарисеи говорили: Он изгоняет бесов <1а>правителем бесов.',2,1,9,34);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Иисус обходил все города и <а>селения, <б>уча в их синагогах, и проповедуя <1>благовестие царства, и исцеляя <2>всякий недуг и всякую болезнь.',2,1,9,35);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, увидев толпы, Он <а>сжалился над ними, потому что они были <1>измученными и брошенными, словно <б>овцы, у которых нет <2>пастыря.',2,1,9,36);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда Он говорит Своим ученикам: <1а>Жатва велика, а работников мало.',2,1,9,37);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, <1>молите <2>Господина жатвы, чтобы Он выгнал <а>работников <3>на Свою жатву.',2,1,9,38);
