insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<1а>Не <2>судите, чтобы не быть судимыми.',2,1,7,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо <1>каким судом судите, таким будете судимы, и какой <а>мерой мерите, такой будет отмерено вам.',2,1,7,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И почему ты смотришь на <а>соринку, которая в глазу твоего брата, а бревна в своём глазу не <1>замечаешь?',2,1,7,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Или как ты можешь сказать своему брату: «Дай я выну соринку из твоего глаза» — а вот, в твоём глазу бревно?',2,1,7,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<1а>Лицемер! Прежде вынь из своего глаза бревно и тогда будешь <2>видеть ясно, чтобы вынуть соринку из глаза твоего брата.',2,1,7,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Не давайте <1>того, что <а>свято, <2б>псам и не бросайте ваши <в>жемчужины перед <г>свиньями, чтобы они не растоптали их ногами и, обернувшись, не разорвали вас.',2,1,7,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<1а>Просите, и вам будет дано; <б>ищите, и найдёте; стучитесь, и вам будет открыто.',2,1,7,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо всякий, кто <1>просит, получает; и тот, кто <2>ищет, находит; и тому, кто <3>стучится, будет открыто.',2,1,7,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Или какой человек из вас, когда его сын попросит у него <а>хлеб, подаст ему камень?',2,1,7,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Или же, когда попросит <а>рыбу, подаст ему змею?',2,1,7,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Если же вы, будучи <а>злыми, умеете давать <б>лагие дары своим детям, то <1>тем более ваш Отец, который на небесах, даст <2б>блага тем, кто просит Его!',2,1,7,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, всё, что хотите, чтобы авам делали люди, так и вы делайте им; ибо это — <1б>закон и пророки.',2,1,7,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<1>Входите через <а>узкие ворота, ибо широки ворота и просторен путь, <2>ведущий к <3б>уничтожению, и много тех, кто входит через них.',2,1,7,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Потому что <1а>узки <б>ворота и стеснён <в>путь, ведущий к <2>жизни, и <г>мало тех, кто находит их.',2,1,7,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Остерегайтесь <а>лжепророков, которые приходят к вам в овечьей одежде, а внутри они — хищные <б>волки.',2,1,7,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('По их <а>плодам узнаете их. Разве собирают с терновника виноград или с чертополоха <б>смоквы?',2,1,7,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Так всякое <а>доброе дерево приносит <б>хорошие плоды, а испорченное дерево приносит <в>плохие плоды.',2,1,7,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Не может доброе дерево приносить плохие плоды, а испорченное дерево приносить хорошие плоды.',2,1,7,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Всякое дерево, не приносящее хорошего плода, срубают и <а>бросают в огонь.',2,1,7,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Так что по их <а>плодам узнаете их.',2,1,7,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Не всякий, кто говорит Мне: «<а>Господь! Господь!» — <1б>войдёт в царство небес, а тот, кто <в>исполняет <г>волю Моего Отца, который на небесах.',2,1,7,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Многие скажут Мне в <1>тот день: «Господь! Господь! Не Твоим ли именем мы пророчествовали, и не Твоим ли именем <а>изгоняли бесов, и не Твоим ли именем совершали многие <б>явления силы?»',2,1,7,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И тогда Я объявлю им: «Я никогда не <1а>знал вас. <б>Отойдите от Меня, творящие <в>беззаконие».',2,1,7,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Итак, <а>всякий, кто слышит эти Мои слова и <б>исполняет их, будет <у>подоблен <в>благоразумному человеку, который построил свой дом на <1г>скале.',2,1,7,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И сошёл <1>дождь, и подступили реки, и подули ветры, и обрушились на тот дом; и он <2>не упал, ибо его основание было положено на скале.',2,1,7,25);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А всякий, кто слышит эти Мои слова и <а>не исполняет их, будет уподоблен человеку неразумному, который построил свой дом на <1>песке.',2,1,7,26);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И сошёл <а>дождь, и подступили реки, и подули ветры, и ударили по тому дому; и он <1>упал, и его падение было велико.',2,1,7,27);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда Иисус окончил эти слова, толпы <а>изумлялись Его учению,',2,1,7,28);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо Он учил их <а>как имеющий <1б>власть, а не как их книжники.',2,1,7,29);
