insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда <1>Иисус был уведён Духом в <а>пустыню, чтобы <2б>искусил Его <3в>дьявол.',2,1,4,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, проведя в <а>посте <1б>сорок дней и сорок ночей, после Он ощутил <в>голод.',2,1,4,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И <1а>искуситель, подойдя, сказал Ему: Если Ты <2б>Сын Божий, скажи, чтобы эти <3>камни стали хлебами.',2,1,4,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Он сказал в ответ: <1>Написано: «<2а>Не одним <3>хлебом будет жить человек, но всяким <4б>словом, исходящим через <5>уста Божьи».',2,1,4,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда дьявол берёт Его в <а>святой город, и ставит Его на <1>крыло <2б>храма,',2,1,4,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И говорит Ему: Если Ты <а>Сын Божий, <1>бросься вниз; ибо <2>написано: «<б>Своим ангелам Он даст повеление о Тебе, и они понесут Тебя на руках, чтобы Ты не споткнулся Твоей ногой о камень».',2,1,4,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Иисус сказал ему: <1>Ещё написано: «<а>Не <2>испытывай Господа, твоего Бога».',2,1,4,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Опять дьявол берёт Его на очень высокую гору и показывает Ему все <1а>царства <б>мира и их <в>славу.',2,1,4,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И он сказал Ему: <1>Всё это я дам Тебе, если Ты, пав, <а>поклонишься мне.',2,1,4,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда Иисус говорит ему: Отойди, <1а>Сатана! Ибо написано: «<б>Господу, твоему Богу, поклоняйся и Ему <2в>одному служи».',2,1,4,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Тогда дьявол <1>оставляет Его, и вот, <2>пришли <а>ангелы и служили Ему.',2,1,4,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А услышав, что <а>Иоанн был отдан под стражу, Он <1>удалился в <б>Галилею.',2,1,4,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, оставив <а>Назарет, Он пришёл и поселился в <б>Капернауме, приморском городе в пределах <в>Завулона и <г>Неффалима,',2,1,4,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Чтобы исполнилось сказанное через пророка Исайю, который говорит:',2,1,4,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('«<а>Земля Завулона и земля Неффалима, путь к морю, за Иорданом, <1>Галилея языческая —',2,1,4,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Народ, сидящий во тьме, увидел <1>великий <а>свет; и сидящим в области и тени смерти — им взошёл свет».',2,1,4,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('С того времени Иисус начал проповедовать и говорить: <1а>Кайтесь, ибо приблизилось царство небес.',2,1,4,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, проходя <а>возле Галилейского <1>моря, Он увидел двух братьев: <б>Симона, называемого Петром, и Андрея, его брата, которые <2>закидывали <3>сеть в море, ибо они были рыбаками.',2,1,4,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он говорит им: <а>Идите за Мной, и Я сделаю вас <1>ловцами людей.',2,1,4,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И они, сразу же оставив сети, <1а>последовали за Ним.',2,1,4,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И, пройдя оттуда дальше, Он увидел других двух братьев: Иакова, сына Зеведея, и <а>Иоанна, его брата, в лодке с Зеведеем, их отцом, которые <1>латали свои сети, — и <б>призвал их.',2,1,4,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И они, сразу же оставив лодку и своего отца, <1а>последовали за Ним.',2,1,4,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И ходил Иисус по всей Галилее, уча в их <1а>синагогах, и проповедуя <2б>благовестие царства, и <в>исцеляя всякий недуг и всякую болезнь в народе.',2,1,4,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И пошёл слух о Нём по всей Сирии; и привели к Нему всех больных, одолеваемых различными недугами и мучениями, и <а>одержимых бесами, и страдающих падучей болезнью, и парализованных, и Он исцелил их.',2,1,4,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И за Ним последовали большие <1а>толпы из Галилеи, <2>Десятиградия, Иерусалима, Иудеи и из-за Иордана.',2,1,4,25);
