insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И когда Он <1>спустился с <а>горы, за Ним последовали большие <б>толпы.',2,1,8,1);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И вот, <1б>прокажённый, подойдя, <2в>поклонялся Ему и говорил: Господь, если Ты хочешь, Ты можешь меня очистить.',2,1,8,2);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он, протянув руку, <1а>коснулся его и сказал: Хочу, очистись! — И он сразу же очистился от проказы.',2,1,8,3);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И говорит ему Иисус: Смотри, <а>никому не говори; а иди, <1>покажи себя <б>священнику и принеси <в>дар, какой заповедал Моисей, для свидетельства им.',2,1,8,4);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И когда Он вошёл в <б>Капернаум, к Нему подошёл <1в>сотник, умоляя Его',2,1,8,5);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И говоря: Господь, мой слуга лежит дома парализованный и жестоко мучится.',2,1,8,6);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он говорит ему: Я приду и исцелю его.',2,1,8,7);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но сотник сказал в ответ: Господь, я не заслуживаю того, чтобы Ты вошёл ко мне под кров, но только скажи <а>слово, и мой слуга будет исцелён.',2,1,8,8);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Ибо и я человек <1>подвластный и имею под своим началом воинов. И говорю этому: «Пойди», и он идёт; а другому: «Приди», и он приходит; и своему рабу: «Сделай это», и он делает.',2,1,8,9);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Иисус, услышав это, удивился и сказал тем, кто следовал за Ним: Истинно говорю вам: <1>ни у кого в Израиле Я не нашёл такой большой веры.',2,1,8,10);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но говорю вам, что многие придут <1а>с востока и запада и возлягут за трапезу с Авраамом, и Исааком, и Иаковом в <2>царстве небес,',2,1,8,11);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А <1>сыновья царства будут <а>выброшены во <2>внешнюю тьму. Там будет <3б>плач и скрежет зубов.',2,1,8,12);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Иисус сказал сотнику: Иди. Как ты поверил, так пусть <а>будет тебе. — И в тот <б>час его слуга был исцелён.',2,1,8,13);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И Иисус, войдя в дом Петра, увидел, что <1>его <б>тёща лежит и у неё горячка.',2,1,8,14);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он <а>коснулся её руки, и горячка оставила её. И она встала и служила Ему.',2,1,8,15);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А с наступлением вечера к Нему привели <1>многих одержимых бесами, и Он изгнал духов <а>словом и всех больных исцелил,',2,1,8,16);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Чтобы <а>исполнилось сказанное через пророка Исайю, который говорит: «<1б>Он Сам взял наши немощи и <в>понёс наши недуги».',2,1,8,17);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А когда Иисус увидел вокруг Себя толпу, Он приказал <1>отправиться на другую сторону.',2,1,8,18);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И один книжник, подойдя, сказал Ему: Учитель, я <1>последую за Тобой, куда бы Ты ни <2>пошёл.',2,1,8,19);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Иисус говорит ему: У лисиц есть норы, и у небесных птиц — гнёзда, но <1а>Сыну Человеческому <2>негде приклонить голову.',2,1,8,20);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А другой из учеников сказал Ему: Господь, <а>позволь мне прежде <1>пойти и похоронить своего отца.',2,1,8,21);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('Но Иисус говорит ему: <а>Следуй за Мной и предоставь <б>мёртвым хоронить своих <1в>мёртвых.',2,1,8,22);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И когда Он вошёл в лодку, Его ученики последовали за Ним.',2,1,8,23);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И вот, на море поднялась сильная <1а>буря, так что лодку накрывало волнами; а Он спал.',2,1,8,24);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И они подошли, разбудили Его и сказали: Господь, <а>спаси, погибаем!',2,1,8,25);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А Он говорит им: Почему вы <а>боязливы, <1б>маловеры? — Тогда Он встал и <2в>возбранил ветрам и морю, и наступила <3>великая <г>тишь.',2,1,8,26);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И люди удивились и говорили: Кто это такой, что даже ветры и море Его <1>слушаются?',2,1,8,27);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('<а>И когда Он прибыл на другую сторону, в Гадаринскую область, Его встретили, выходя из гробниц, двое одержимых бесами, чрезвычайно свирепые, так что никто не мог пройти той дорогой.',2,1,8,28);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И вот, они закричали: <1а>Что Тебе до нас, <2б>Сын Божий? Ты пришёл сюда <3>прежде <в>времени мучить нас?',2,1,8,29);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А вдали от них паслось большое стадо свиней.',2,1,8,30);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И бесы <1>умоляли Его: Если Ты изгоняешь нас, пошли нас в стадо свиней.',2,1,8,31);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И Он сказал им: <1>Идите! — И они, выйдя, пошли в свиней. И вот, всё стадо <2>устремилось с крутизны в море, и свиньи погибли в водах.',2,1,8,32);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('А те, что пасли их, убежали и, пойдя в город, сообщили обо всём, включая то, что произошло с людьми, одержимыми бесами.',2,1,8,33);
insert into bible_verse (text, testament_id, book_id, chapter, verse) values ('И вот, весь город вышел навстречу Иисусу, и, увидев Его, они умоляли, чтобы Он <1а>удалился от их пределов.',2,1,8,34);
